Example of using GeoJSON data sources

# Ecosystems Map

In [1]:
from rle_python_gee.ecosystems import Ecosystems
from rle_python_gee.aoo import make_aoo

In [2]:
TEST_EXPORTS = True

In [3]:
# ecosystems = Ecosystems.from_geojson('../tests/test_data/null_island.geojson', ecosystem_column='ECO_CODE')
ecosystems = Ecosystems.from_geojson(
    '/Users/tylere/Documents/GitHub/RLE-Assessment/rle-python-gee/tests/test_data/colombia_ecosystems.shp',
    ecosystem_column='ECO_CODE'
)
ecosystems.load()
ecosystems

EcosystemsGeoJSON(data='/Users/tylere/Documents/GitHub/RLE-Assessment/rle-python-gee/tests/test_data/colombia_ecosystems.shp')

In [4]:
ecosystems.head()

,OBJECTID,COD,ECRG,ECO_NAME,EFG_Etter,EFG1,EFG2,Shape_Leng,Shape_Area,Glob_Typol,GETyp_CODn,COD_new,ECO_CODE,geometry
0,1,A1,Guaj-Barr xs,Guajira-Barranquilla xeric scrub,T5.2,T5.2,T5.2,17408.006950,9.082025e+04,T5.2_Guaj-Barr xs_A1,T5.2_Guaj-Barr xs_A1,A1,T5.2.1,"POLYGON ((815932.206 1262032.835, 811874.343 1..."
1,2,A1,Guaj-Barr xs,Guajira-Barranquilla xeric scrub,T5.2,T5.2,T5.2,8012.320043,2.116378e+06,T5.2_Guaj-Barr xs_A1,T5.2_Guaj-Barr xs_A1,A1,T5.2.1,"POLYGON ((776254.963 1283968.923, 776266.003 1..."
2,3,A1,Guaj-Barr xs,Guajira-Barranquilla xeric scrub,T5.2,T5.2,T5.2,11223.429833,4.311710e+06,T5.2_Guaj-Barr xs_A1,T5.2_Guaj-Barr xs_A1,A1,T5.2.1,"POLYGON ((779083.69 1284194.735, 779180.978 12..."
3,4,A1,Guaj-Barr xs,Guajira-Barranquilla xeric scrub,T5.2,T5.2,T5.2,9122.025355,3.027278e+06,T5.2_Guaj-Barr xs_A1,T5.2_Guaj-Barr xs_A1,A1,T5.2.1,"POLYGON ((767944.842 1286579.007, 767920.445 1..."
4,5,A1,Guaj-Barr xs,Guajira-Barranquilla xeric scrub,T5.2,T5.2,T5.2,26858.921669,3.987598e+06,T5.2_Guaj-Barr xs_A1,T5.2_Guaj-Barr xs_A1,A1,T5.2.1,"POLYGON ((739532.236 1288429.536, 739533.146 1..."

In [5]:
ecosystems.unique_ecosystems()

['F1.1.1',
 'F1.1.2',
 'F1.1.3',
 'F1.1.4',
 'F1.1.5',
 'F1.1.6',
 'F1.2.1',
 'F1.2.2',
 'F2.1.1',
 'F2.2.1',
 'F2.3.1',
 'F3.1.1',
 'FM1.2.1',
 'MFT1.1.1',
 'MFT1.1.2',
 'MFT1.1.3',
 'MFT1.2.1',
 'MFT1.2.2',
 'T1.1.1',
 'T1.1.10',
 'T1.1.11',
 'T1.1.12',
 'T1.1.13',
 'T1.1.14',
 'T1.1.15',
 'T1.1.16',
 'T1.1.17',
 'T1.1.18',
 'T1.1.19',
 'T1.1.2',
 'T1.1.20',
 'T1.1.21',
 'T1.1.22',
 'T1.1.23',
 'T1.1.24',
 'T1.1.25',
 'T1.1.26',
 'T1.1.27',
 'T1.1.3',
 'T1.1.4',
 'T1.1.5',
 'T1.1.6',
 'T1.1.7',
 'T1.1.8',
 'T1.1.9',
 'T1.2.1',
 'T1.2.10',
 'T1.2.11',
 'T1.2.12',
 'T1.2.13',
 'T1.2.14',
 'T1.2.15',
 'T1.2.16',
 'T1.2.17',
 'T1.2.18',
 'T1.2.19',
 'T1.2.2',
 'T1.2.20',
 'T1.2.21',
 'T1.2.22',
 'T1.2.23',
 'T1.2.24',
 'T1.2.25',
 'T1.2.26',
 'T1.2.27',
 'T1.2.28',
 'T1.2.3',
 'T1.2.4',
 'T1.2.5',
 'T1.2.6',
 'T1.2.7',
 'T1.2.8',
 'T1.2.9',
 'T1.3.1',
 'T1.3.10',
 'T1.3.11',
 'T1.3.12',
 'T1.3.13',
 'T1.3.14',
 'T1.3.15',
 'T1.3.16',
 'T1.3.17',
 'T1.3.18',
 'T1.3.19',
 'T1.3.2',
 'T1.3.20',
 'T1.3.21',
 'T1.3.22',
 'T1.3.23',
 'T1.3.24',
 'T1.3.25',
 'T1.3.26',
 'T1.3.27',
 'T1.3.28',
 'T1.3.29',
 'T1.3.3',
 'T1.3.30',
 'T1.3.31',
 'T1.3.32',
 'T1.3.33',
 'T1.3.34',
 'T1.3.35',
 'T1.3.36',
 'T1.3.37',
 'T1.3.38',
 'T1.3.39',
 'T1.3.4',
 'T1.3.40',
 'T1.3.41',
 'T1.3.42',
 'T1.3.43',
 'T1.3.44',
 'T1.3.5',
 'T1.3.6',
 'T1.3.7',
 'T1.3.8',
 'T1.3.9',
 'T1.4.1',
 'T1.4.2',
 'T1.4.3',
 'T3.1.1',
 'T3.1.2',
 'T4.2.1',
 'T4.2.10',
 'T4.2.11',
 'T4.2.12',
 'T4.2.2',
 'T4.2.3',
 'T4.2.4',
 'T4.2.5',
 'T4.2.6',
 'T4.2.7',
 'T4.2.8',
 'T4.2.9',
 'T5.2.1',
 'T5.2.2',
 'T5.2.3',
 'T6.5.1',
 'T6.5.2',
 'T6.5.3',
 'T6.5.4',
 'T6.5.5',
 'T6.5.6',
 'TF1.1.1',
 'TF1.1.2',
 'TF1.1.3',
 'TF1.1.4',
 'TF1.1.5',
 'TF1.1.6',
 'TF1.1.7',
 'TF1.1.8',
 'TF1.1.9',
 'TF1.3.1',
 'TF1.3.2',
 'TF1.3.3',
 'TF1.4.1',
 'TF1.4.2',
 'TF1.4.3',
 'TF1.5.1',
 'TF1.5.2',
 'TF1.5.3']

In [6]:
ecosystems.to_map()

In [7]:
if TEST_EXPORTS:
    ecosystems.to_parquet('tmp/ecosystems.parquet')

In [8]:
if TEST_EXPORTS:    
    import ee
    ee.Initialize(project='goog-rle-assessments')
    task_id = ecosystems.to_ee_feature_collection(
        'projects/goog-rle-assessments/assets/temp/ecosystems',
        gcs_bucket='rle_test_bucket_1'
    )
    print(f'{task_id=}')

task_id={'id': '3YOHIILGUHEURNGWWP6BRI3R', 'name': 'projects/goog-rle-assessments/operations/3YOHIILGUHEURNGWWP6BRI3R', 'started': 'OK'}

# AOO Grid

In [9]:
aoo_grid = make_aoo(ecosystems).compute()
aoo_grid

AOOGridVectorLocal(cell_count=11881, aoo_km2=1188100)

In [10]:
aoo_grid.grid_cells.head()

,grid_col,grid_row,geometry,count_geoms,count_ecosystems,F1_1_1,F1_1_2,F1_1_3,F1_1_4,F1_1_5,...,TF1_1_9,TF1_3_1,TF1_3_2,TF1_3_3,TF1_4_1,TF1_4_2,TF1_4_3,TF1_5_1,TF1_5_2,TF1_5_3
0,-880,17,"POLYGON ((-78.96191 1.53761, -78.96191 1.62808...",9,3,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-880,18,"POLYGON ((-78.96191 1.62808, -78.96191 1.71855...",7,3,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-879,16,"POLYGON ((-78.87208 1.44714, -78.87208 1.53761...",1,1,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-879,17,"POLYGON ((-78.87208 1.53761, -78.87208 1.62808...",19,4,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-879,18,"POLYGON ((-78.87208 1.62808, -78.87208 1.71855...",9,5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
aoo_grid.to_map()

VBox(children=(<lonboard._map.Map object at 0x115890bc0>, VBox(children=(ErrorOutput(), ErrorOutput(), ErrorOu…

In [16]:
aoo_grid.filter_by_ecosystem('F1_1_2', threshold=0.00).to_map()

VBox(children=(<lonboard._map.Map object at 0x11c6a40e0>, VBox(children=(ErrorOutput(), ErrorOutput(), ErrorOu…

In [17]:
if TEST_EXPORTS:
    aoo_grid.to_parquet('/tmp/aoo_grid.parquet')

In [18]:
if TEST_EXPORTS:
    task_id = aoo_grid.to_ee_feature_collection(
        'projects/goog-rle-assessments/assets/temp/aoo_grid',
        gcs_bucket='rle_test_bucket_1'
    )
    print(f'{task_id=}')

task_id={'id': '4LKXC6OXRC6JQ74QZWJDOTK5', 'name': 'projects/goog-rle-assessments/operations/4LKXC6OXRC6JQ74QZWJDOTK5', 'started': 'OK'}

# AOO Grid Polygons

In [19]:
aoo_grid_polygons = aoo_grid.to_polygons().compute()
aoo_grid_polygons

AOOGridPolygonVectorLocal(polygons=104944)

In [20]:
aoo_grid_polygons.to_map()

In [21]:
if TEST_EXPORTS:
    # Write the grid polygons to a parquet file
    aoo_grid_polygons.to_parquet('/tmp/aoo_grid_polygons.parquet')

In [22]:
if TEST_EXPORTS:
    task_id = aoo_grid_polygons.to_ee_feature_collection(
        'projects/goog-rle-assessments/assets/temp/aoo_grid_polygons',
        gcs_bucket='rle_test_bucket_1'
    )
    print(f'{task_id=}')

task_id={'id': '7MFGYRSTNNRTKG5XHU3P66ZQ', 'name': 'projects/goog-rle-assessments/operations/7MFGYRSTNNRTKG5XHU3P66ZQ', 'started': 'OK'}

# Layered Map

In [23]:
from lonboard import Map

Map(layers=ecosystems.to_layer() + aoo_grid_polygons.to_layer())

ValueError: Dataset has 50,160 features, which is too many to display interactively. Upload to Earth Engine with .to_ee_feature_collection(asset_id) and use Ecosystems.from_gee_feature_collection() for tile-based visualization.